### ISSUE TITLE
Error with chat parking

### ISSUE THREAD

**Issue by JuanSanabria-SEAQ** [twilio-professional-services/flex-project-template#412]
Good day I am communicating by this means because we currently have a problem with our plugin WhatsApp chat parking (API conversations) where at the time that an agent accepts the task of a chat parked in some occasions appears that is not part of the conversation the agent and in others comes normal conversation would like to know why this happens and how I can fix it.

![imagen_2023-10-27_144758730](https://github.com/twilio-professional-services/flex-project-template/assets/136838656/7ed6dc2d-216f-494a-b648-23b474bf0b47)
![imagen_2023-10-27_144811716](https://github.com/twilio-professional-services/flex-project-template/assets/136838656/92d6989f-3fb4-46c2-bde0-8437b97763a3)

**Comment by dremin** [comment]
Hello!
There is a known race condition in Flex UI that causes this to occur. Basically, when parking, a Redux action to update the conversation sometimes occurs _after_ the action to unload the conversation, which places (an invalid version of) the conversation back into Redux, so when unparking, Flex doesn't load the conversation, because it thinks it's already loaded.

We have implemented a workaround [at these lines of code](https://github.com/twilio-professional-services/flex-project-template/blob/main/plugin-flex-ts-template-v2/src/feature-library/park-interaction/actions/ParkInteraction.ts#L48-L59) which forces the unload after 2 seconds, so that when unparking, the conversation is loaded properly. You are likely seeing this issue due to that 2-second timer either being too long, or too short. I would suggest playing with the timer here to see if a different duration works better for you. If you are not able to find a reliable value for this, I would recommend submitting a support ticket to have this fixed from the product side.

**Comment by dremin** [comment]
Hi @JuanSanabria-SEAQ, please try Flex UI 2.5.0. This issue should be resolved in that version.
