### ISSUE TITLE
Error with chat-to-video

### ISSUE THREAD

**Issue by GuilleFibo** [twilio-professional-services/flex-project-template#424]
Trying to use chat-to-video-escalation, yes I could install it but when I test it, it's not working because my shared videoroom url is not found, and yes searching, someone knows why this happens or how to fix it? I need an index.html file into my serverless chat-to-video-escalation folder, but I don't know where I can get it
![twilioVideocall004](https://github.com/twilio-professional-services/flex-project-template/assets/78044905/9737237f-6785-4e65-b0a9-9a0105a9b9e7)
![twilioVideocall003](https://github.com/twilio-professional-services/flex-project-template/assets/78044905/4eef0294-7906-425f-8d43-01ed6cc21151)
![twilioVideocall002](https://github.com/twilio-professional-services/flex-project-template/assets/78044905/8030838a-1923-426c-b2cc-d0de1e96896f)
![twilioVideocall001](https://github.com/twilio-professional-services/flex-project-template/assets/78044905/e6cdf9e7-5937-4069-b45f-ea2120aca4db)

**Comment by dremin** [comment]
It looks like you don't have a compiled version of the video app deployed to serverless, which you'll need for this to work. The chat-to-video app is compiled and copied to the serverless-functions assets directory when the postinstall script runs (either when performing `npm install` in the root directory or when running `npm run postinstall` manually). It also happens when running `npm run deploy` in the video app's package directory. Hopefully this helps; the GitHub actions scripts also do this out of the box.

**Comment by dremin** [comment]
Closing due to no response--feel free to re-open if necessary. Thanks!
