### ISSUE TITLE
Agent #1 Full Name being exposed to customer (instead of public_identity) being exposed upon cold transfer to Agent #2

### ISSUE THREAD

**Issue by alankleindev** [twilio-professional-services/flex-project-template#448]
We identified an issue that happens on the front end with regards to the Agent Username showed to the customer. The initial engagement between the customer and the agent properly shows the Agents public_identity to the customer.

However, when the agent transfers the chat to another agent, the customer suddenly sees the real name of the first agent in the chat transcript and public_identity of the second agent which is quite concerning, as we don't want our agents real names being exposed directly to the customer.

**Comment by dremin** [comment]
Hi @alankleindev, I reviewed this and I believe the issue is with the webchat widget, rather than the plugin. It seems the widget forgets the worker's attributes after they have left the conversation. I would recommend opening an issue on the [webchat widget repo](https://github.com/twilio/twilio-webchat-react-app) so the team that maintains it can review. Thanks!
