### ISSUE TITLE
Cold Transfer Failing without error handling

### ISSUE THREAD

**Issue by chaosloth** [twilio-professional-services/flex-project-template#580]
Using the custom transfer directory, cold transferred calls that are to destinations that do not have voice geo-permissions enabled are failing to connect. The agent is left with the impression that the cold transfer was successful, however the end-user is disconnected.

The issue is that geo-permissions are applied correctly but the `functions/common/twilio-wrappers/programmable-voice.private.js` blindly executes the transfer without checking if an error (such as `[13227]`) has occurred and return that error to the Flex UI.

# Steps to replicate:
- Enable geo permissions for a given country
- In Flex receive or place a call
- Attempt to cold-transfer said call to this blocked country

**Comment by dremin** [comment]
We can't handle the error code, because at that point it is already too late. However, we might be able to make another API request [to the dialing permissions API](https://www.twilio.com/docs/voice/api/dialingpermissions-country-resource) using the country code returned by the [existing lookup API](https://github.com/twilio-professional-services/flex-project-template/blob/main/serverless-functions/src/functions/common/flex/phone-numbers/validate-phone-number.js) response, before we attempt the transfer.

Hopefully admins aren't configuring numbers that nobody is allowed to dial 😅
